version: '3.1'

services:
  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - mysql-data:/var/lib/mysql5
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wordpress-network

  wordpress:
    depends_on: 
      - mysql_db
    image: wordpress:5.9.1-fpm-alpine
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql_db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress-network

  phpmyadmin:
    image: phpmyadmin:5.1.3-fpm-alpine
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    networks:
      - wordpress-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - wordpress-network


  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email zach@azntaiji.com --agree-tos --force-renewal -d zachtaiji.com -d www.zachtaiji.com

volumes:
  certbot-etc:
  wordpress:
  mysql-data:

networks:
  wordpress-network:
    driver: bridge  